### ISSUE TITLE
Formatting Pandemic tracker

### ISSUE THREAD

**Issue by BattlePants-max** [OldStarchy/pandemic_tracker#2]
Version: 358d182

Doesn’t quite show as full as it should??
Otherwise a nice app improvement from earlier
![0F1394E7-A3A5-4693-AA96-136A0D58A81C](https://github.com/OldStarchy/pandemic_tracker/assets/106159796/a0e638a9-18f1-4006-9dc0-cea607f26ffb)

**Comment by OldStarchy** [comment]
Fixed in latest version
